services:
  php:
    image: yiisoftware/yii2-php:8.3-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  db:
    image: mariadb
    # restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: yii2basic
    ports:
      - '3307:3306'
